name: davinci
description: A package to convert any widget to an image which can be saved locally or can be shared to other apps and chats.
version: 2.1.3
homepage: https://github.com/Imgkl/davinci

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  gallery_saver: 
    git:
      url: git://github.com/kaiquecruz/gallery_saver.git
      ref: 'main' 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

